In [4]:
import numpy as np

A = np.array([[2,-3,1],[3,1,1],[-1,-2,-1]])
b = np.array([2,-1,1])

x,y,z = np.linalg.solve(A,b)
print((x,y,z))

(np.float64(-0.3333333333333333), np.float64(-0.6666666666666666), np.float64(0.6666666666666667))


In [5]:
C = np.array([3,-1,2]) 
D = np.array([0,-1,1])

E = C@D
print(E)

3


In [12]:
F = np.array([[2,-3,1],[-2,-1,4],[0,2,2],[-1,-3,-2]])
G = np.array([[3,-2,1],[1,-1,2],[-2,2,0]])
I = np.array([1,2,3])
H = np.matmul(F,G)
print(H)
J = np.matmul(H,I)
print(f'Displaying J: {J}')

[[  1   1  -4]
 [-15  13  -4]
 [ -2   2   4]
 [ -2   1  -7]]
Displaying J: [ -9  -1  14 -21]


In [14]:
laq1 = np.array([[1,-3,1],[2,-8,8],[-6,3,-15]])
laq2 = np.array([4,-2,9])

l,m,n = np.linalg.solve(laq1,laq2)
print(l,m,n)

3.0000000000000013 -1.0000000000000002 -2.0000000000000004


In [15]:
inverse = np.array([[2,4,-2],[-2,0,1],[3,-3,0]])
print(np.linalg.inv(inverse))

[[0.5        1.         0.66666667]
 [0.5        1.         0.33333333]
 [1.         3.         1.33333333]]
